#!/usr/bin/dh-exec
usr/bin/mesa-overlay-control.py
usr/bin/mesa-screenshot-control.py
usr/lib/*/libVkLayer_*.so
usr/lib/*/libvulkan_*.so
[amd64 arm64 armhf i386] usr/share/drirc.d/00-turnip-defaults.conf
[amd64 arm64 armhf i386 ppc64 riscv64 x32] usr/share/drirc.d/00-nvk-defaults.conf
[amd64 arm64 i386] usr/share/drirc.d/00-hk-defaults.conf
[amd64 i386] usr/share/drirc.d/00-anv-defaults.conf
[amd64 i386] usr/share/drirc.d/00-hasvk-defaults.conf
[arm64 armhf] usr/share/drirc.d/00-panvk-defaults.conf
[arm64 armhf] usr/share/drirc.d/00-v3dv-defaults.conf
usr/share/drirc.d/00-lavapipe-defaults.conf
usr/share/drirc.d/00-radv-defaults.conf
usr/share/drirc.d/00-venus-defaults.conf
usr/share/vulkan/explicit_layer.d/*.json
usr/share/vulkan/icd.d/*.json
usr/share/vulkan/implicit_layer.d/*.json
