usr/lib/*/libgallium-*.so
#[amd64 arm64] usr/share/drirc.d/00-d3d12-defaults.conf
#[amd64 arm64 armhf i386] usr/share/drirc.d/00-msm-defaults.conf
#[amd64 arm64 i386] usr/share/drirc.d/00-asahi-defaults.conf
#[amd64 i386] usr/share/drirc.d/00-crocus-defaults.conf
#[amd64 arm64 i386] usr/share/drirc.d/00-iris-defaults.conf
#[arm64 armhf] usr/share/drirc.d/00-panfrost-defaults.conf
#[arm64 armhf] usr/share/drirc.d/00-v3d-defaults.conf
#usr/share/drirc.d/00-r300-defaults.conf
#usr/share/drirc.d/00-r600-defaults.conf
#[amd64 arm64 armhf i386 loong64 ppc64el] usr/share/drirc.d/00-radeonsi-defaults.conf
#usr/share/drirc.d/00-virtio_gpu-defaults.conf
#usr/share/drirc.d/00-vmwgfx-defaults.conf
#usr/share/drirc.d/00-zink-defaults.conf
